stages:
  - test
  - build

test:
  stage: test
  image: python:3.10
  script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pytest -q || echo "No tests found, skipping."

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD"
  script:
    - docker build -t $DOCKER_HUB_USERNAME/streamlit-app:latest .
    - docker push $DOCKER_HUB_USERNAME/streamlit-app:latest
    - docker tag $DOCKER_HUB_USERNAME/streamlit-app:latest $DOCKER_HUB_USERNAME/streamlit-app:$CI_COMMIT_SHORT_SHA
    - docker push $DOCKER_HUB_USERNAME/streamlit-app:$CI_COMMIT_SHORT_SHA