stages:
  - test
  - build
  - publish

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE:latest
  DOCKERHUB_IMAGE: $DOCKERHUB_USERNAME/streamlit-bike:latest

test:
  stage: test
  image: python:3.10
  script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pytest -q || echo "No tests found, skipping."


build:
  image: docker:24
  stage: build
  services:
    - name: docker:24-dind
      command: ["--tls=false"]
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker build -t $IMAGE_NAME .
    - docker tag $IMAGE_NAME $DOCKERHUB_IMAGE
  only:
    - main

publish-gitlab:
  image: docker:24
  stage: publish
  services:
    - name: docker:24-dind
      command: ["--tls=false"]
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" $CI_REGISTRY --password-stdin
    - docker push $IMAGE_NAME
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - main
  needs: ["build"]

publish-dockerhub:
  image: docker:24
  stage: publish
  services:
    - name: docker:24-dind
      command: ["--tls=false"]
  variables:
    DOCKERHUB_IMAGE: $DOCKERHUB_USERNAME/streamlit-app:$CI_COMMIT_SHORT_SHA
  script:
    - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker tag $IMAGE_NAME $DOCKERHUB_IMAGE
    - docker tag $IMAGE_NAME $DOCKERHUB_USERNAME/streamlit-app:latest
    - docker push $DOCKERHUB_IMAGE
    - docker push $DOCKERHUB_USERNAME/streamlit-app:latest
  only:
    - main
  needs: ["build"]
