stages:
  - test
  - build

test:
  stage: test
  image: python:3.10
  script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pytest -q || echo "No tests found, skipping."

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u "thom1100" -p "$DOCKER_HUB_PASSWORD"
  script:
    - docker build -t $thom1100/streamlit-app:latest .
    - docker push $thom1100/streamlit-app:latest
    - docker tag $thom1100/streamlit-app:latest $thom1100/streamlit-app:$CI_COMMIT_SHORT_SHA
    - docker push $thom1100/streamlit-app:$CI_COMMIT_SHORT_SHA